lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  def get_current_user(conn, _params) do
    user_id = get_session(conn, :user_id)
    user = TaskTracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/board", PageController, :board
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
    resources "/users", UserController
    resources "/tasks", TaskController
  end

  scope "/api/v1", TaskTrackerWeb do
    pipe_through :api
    resources "/manages", ManageController, except: [:new, :edit]
    resources "/blocks", TimeBlockController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

lib/task_tracker_web/views/layout_view.ex
defmodule TaskTrackerWeb.LayoutView do
  use TaskTrackerWeb, :view
end

lib/task_tracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>TaskTracker</title>
        <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    </head>

    <body>
        <div class="row">
            <div class="col-3 offset-9">
                <%= if @current_user do %>
                    <p>
                        Logged in as: <%= @current_user.name %> |
                        <%= link "Log out", to: "/session", method: :delete %>
                    </p>
                <% else %>
                    <p>Not currently logged in.</p>
                <% end %>
            </div>
        </div>

        <div class="row">
            <div class="col-3 offset-9">
                <%= if @current_user do %>
                    <span><%= link "Board", to: page_path(@conn, :board) %></span>
                    <span><%= link "Tasks", to: task_path(@conn, :index) %></span>
                    <span><%= link "Users", to: user_path(@conn, :index) %></span>
                <% end %>
            </div>
        </div>

        <div class="container">

            <%= if get_flash(@conn, :info) do %>
                <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
            <% end %>
            <%= if get_flash(@conn, :error) do %>
                <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
            <% end %>

            <main role="main">
            <%= render @view_module, @view_template, assigns %>
            </main>

        </div> <!-- /container -->
        <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    </body>
</html>